// <auto-generated />
using System;
using ControlTerritorial.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ControlTerritorial.Infrastructure.Migrations
{
    [DbContext(typeof(DbContextControlTerritorial))]
    partial class DbContextControlTerritorialModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ControlTerritorial.Domain.Entities.Escuela", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Direccion")
                        .HasColumnType("text");

                    b.Property<string>("NombreEstablecimiento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Escuelas");
                });

            modelBuilder.Entity("ControlTerritorial.Domain.Entities.Mesa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EscuelaId")
                        .HasColumnType("integer");

                    b.Property<int>("NroMesa")
                        .HasColumnType("integer");

                    b.Property<string>("Orden")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EscuelaId");

                    b.ToTable("Mesas");
                });

            modelBuilder.Entity("ControlTerritorial.Domain.Entities.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DNI")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("EscuelaId")
                        .HasColumnType("integer");

                    b.Property<int?>("LiderId")
                        .HasColumnType("integer");

                    b.Property<int?>("MesaId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Rol")
                        .HasColumnType("integer");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EscuelaId");

                    b.HasIndex("LiderId");

                    b.HasIndex("MesaId");

                    b.ToTable("Personas");
                });

            modelBuilder.Entity("ControlTerritorial.Domain.Entities.Vehiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChoferId")
                        .HasColumnType("integer");

                    b.Property<string>("Dominio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RegistradoPorId")
                        .HasColumnType("integer");

                    b.Property<int>("TipoVehiculo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ChoferId");

                    b.HasIndex("RegistradoPorId");

                    b.ToTable("Vehiculos");
                });

            modelBuilder.Entity("ControlTerritorial.Domain.Entities.Mesa", b =>
                {
                    b.HasOne("ControlTerritorial.Domain.Entities.Escuela", "Escuela")
                        .WithMany("Mesas")
                        .HasForeignKey("EscuelaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Escuela");
                });

            modelBuilder.Entity("ControlTerritorial.Domain.Entities.Persona", b =>
                {
                    b.HasOne("ControlTerritorial.Domain.Entities.Escuela", "Escuela")
                        .WithMany("Personas")
                        .HasForeignKey("EscuelaId");

                    b.HasOne("ControlTerritorial.Domain.Entities.Persona", "Lider")
                        .WithMany("Subordinados")
                        .HasForeignKey("LiderId");

                    b.HasOne("ControlTerritorial.Domain.Entities.Mesa", "Mesa")
                        .WithMany("Personas")
                        .HasForeignKey("MesaId");

                    b.Navigation("Escuela");

                    b.Navigation("Lider");

                    b.Navigation("Mesa");
                });

            modelBuilder.Entity("ControlTerritorial.Domain.Entities.Vehiculo", b =>
                {
                    b.HasOne("ControlTerritorial.Domain.Entities.Persona", "Chofer")
                        .WithMany()
                        .HasForeignKey("ChoferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ControlTerritorial.Domain.Entities.Persona", "RegistradoPor")
                        .WithMany()
                        .HasForeignKey("RegistradoPorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chofer");

                    b.Navigation("RegistradoPor");
                });

            modelBuilder.Entity("ControlTerritorial.Domain.Entities.Escuela", b =>
                {
                    b.Navigation("Mesas");

                    b.Navigation("Personas");
                });

            modelBuilder.Entity("ControlTerritorial.Domain.Entities.Mesa", b =>
                {
                    b.Navigation("Personas");
                });

            modelBuilder.Entity("ControlTerritorial.Domain.Entities.Persona", b =>
                {
                    b.Navigation("Subordinados");
                });
#pragma warning restore 612, 618
        }
    }
}
